replicaCount: 2

image:
  repository: ghcr.io/prajwalbadigerrr/url-shortener-devops
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000

# SECURITY: Secrets injected as environment variables from Kubernetes secret
env:
  - name: APP_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: vault-token
        key: token

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

health:
  path: /health
  port: 5000