apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: url-shortener-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: url-shortener  
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "web"        # ← string name, not number
      path: /metrics
      interval: 15s